logging:
  pattern:
    console: "%clr([%d{MM-dd-yyyy HH:mm:ss}]){blue} %clr([%0.-1level]) %clr([%-15.-15t]){cyan} %clr(%-40.40logger{39}){blue} %clr(:){red} %clr(%m){faint}%n"
spring:
  application:
    token:
  jpa:
    generate-ddl: "true"
    open-in-view: "false"
    hibernate:
      ddl-auto: "none"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
  datasource:
    url:
    password:
    username:
